server:
  port: 9009
jwt:
  secret: javainuse
# H2
spring:
  h2:
    console:
      path: /h2
      enabled: true

  # Datasource
  datasource:
    url: jdbc:h2:file:~/spring-boot-h2-db-new
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
